// travelFacts.js
export const travelFacts = [
  "Ciekawostka: Najkrótszy lot na świecie trwa tylko 2 minuty – między szkockimi wyspami Westray i Papa Westray.",
  "Ciekawostka: Pustynia Sahara była kiedyś zieloną sawanną, pełną zwierząt i rzek.",
  "Ciekawostka: Na Malcie znajduje się więcej zabytkowych budowli na metr kwadratowy niż gdziekolwiek indziej na świecie.",
  "Ciekawostka: W Wenecji jest około 400 mostów, ale tylko jeden z nich ma nazwę 'Most Westchnień'.",
  "Ciekawostka: Australia jest szersza niż Księżyc.",
  "Ciekawostka: Najwyższy wodospad na świecie, Salto Angel, jest blisko 15 razy wyższy niż Niagara.",
  "Ciekawostka: Rosja obejmuje 11 stref czasowych – to najwięcej na świecie!",
  "Ciekawostka: Arabia Saudyjska to największy kraj na świecie, w którym nie ma ani jednej stałej rzeki.",
  "Ciekawostka: Singapur jest jednym z niewielu państw-miast na świecie, w którym nie ma rolnictwa.",
  "Ciekawostka: W Finlandii jest więcej saun niż samochodów osobowych – to ponad 3 miliony saun na 5,5 mln mieszkańców!",
  "Ciekawostka: Najrzadziej odwiedzanym krajem świata jest Nauru – rocznie przyjeżdża tam tylko około 200 turystów.",
  "Ciekawostka: W Mongolii żyje więcej koni niż ludzi. To kraj o najniższej gęstości zaludnienia na świecie.",
  "Ciekawostka: Watykan jest tak mały, że cały kraj można przejść pieszo w mniej niż godzinę.",
  "Ciekawostka: Najkrótsza rzeka świata, D-River w USA, ma zaledwie 37 metrów długości.",
  "Ciekawostka: W Japonii znajduje się hotel Nishiyama Onsen Keiunkan, który działa nieprzerwanie od 705 roku n.e.!",
  "Ciekawostka: Papuę-Nową Gwineę zamieszkują społeczności posługujące się ponad 820 różnymi językami.",
  "Ciekawostka: W Singapurze rzucenie gumy do żucia na ulicę może skończyć się bardzo wysokim mandatem.",
  "Ciekawostka: Kanada posiada więcej jezior niż wszystkie inne kraje świata razem wzięte.",
  "Ciekawostka: Francja jest najczęściej odwiedzanym krajem na świecie, ale to w Las Vegas znajduje się najwięcej pokoi hotelowych.",
  "Ciekawostka: Central Park w Nowym Jorku jest najczęściej filmowanym miejscem na świecie.",
  "Ciekawostka: Pustynia Atakama w Chile jest tak sucha, że w niektórych jej rejonach nigdy nie odnotowano opadów deszczu.",
  "Ciekawostka: Najniższym krajem świata są Malediwy – ich średnia wysokość to zaledwie 1,5 metra nad poziomem morza.",
  "Ciekawostka: W Islandii nie ma ani jednej restauracji McDonald's – ostatnią zamknięto w 2009 roku.",
  "Ciekawostka: Monako jest mniejsze niż Central Park w Nowym Jorku.",
  "Ciekawostka: W Etiopii kalendarz ma 13 miesięcy, a obecnie jest tam rok 2018!",
  "Ciekawostka: San Francisco ma najbardziej krzywą ulicę świata – Lombard Street, która ma aż 8 ostrych zakrętów.",
  "Ciekawostka: W Szwajcarii posiadanie tylko jednej świnki morskiej jest nielegalne, bo te zwierzęta czują się samotne.",
  "Ciekawostka: Największa piramida na świecie nie znajduje się w Egipcie, lecz w Meksyku – to Wielka Piramida w Cholula.",
  "Ciekawostka: W Tajlandii co roku odbywa się festiwal, podczas którego przygotowuje się ogromną ucztę dla... lokalnych małp.",
  "Ciekawostka: Na Antarktydzie nie ma stref czasowych – naukowcy zazwyczaj używają czasu kraju, z którego wyruszyli.",
  "Ciekawostka: W Holandii jest więcej rowerów niż mieszkańców.",
  "Ciekawostka: W całym stanie Wyoming w USA znajdują się tylko dwa zestawy schodów ruchomych.",
  "Ciekawostka: Bhutan to jedyny kraj na świecie, który mierzy 'Szczęście Narodowe Brutto' zamiast tylko PKB.",
  "Ciekawostka: Najstarsze drzewo na świecie, sosna o imieniu Matuzalem w Kalifornii, ma ponad 4800 lat.",
  "Ciekawostka: W Wenecji gondolierzy muszą posiadać licencję, a ich liczba jest ściśle ograniczona do około 400.",
  "Ciekawostka: Głowa Statuy Wolności została pierwotnie zbudowana w Paryżu i zaprezentowana na wystawie światowej.",
  "Ciekawostka: Na wyspie Reunion wulkany są tak aktywne, że powierzchnia wyspy regularnie się powiększa.",
  "Ciekawostka: W Dubaju policja używa supersamochodów, takich jak Bugatti, Lamborghini i Ferrari, aby patrolować turystyczne dzielnice.",
  "Ciekawostka: Port lotniczy w Gibraltarze ma pas startowy, który przecina normalną ulicę z ruchem samochodowym.",
  "Ciekawostka: W Brazylii znajduje się wyspa Ilha da Queimada Grande, na którą wstęp jest zakazany, bo żyje tam do 5 jadowitych węży na metr kwadratowy.",
  "Ciekawostka: W Korei Południowej uważa się, że spanie przy włączonym wentylatorze w zamkniętym pokoju może być niebezpieczne.",
  "Ciekawostka: Największa lustrzana powierzchnia na świecie to solnisko Salar de Uyuni w Boliwii – po deszczu wygląda jak gigantyczne lustro nieba.",
  "Ciekawostka: Wieża Eiffla może być o 15 cm wyższa latem z powodu rozszerzalności cieplnej metalu.",
  "Ciekawostka: W Kanadzie istnieje miasto Churchill, gdzie mieszkańcy nie zamykają samochodów, aby przechodnie mogli się w nich schować przed niedźwiedziami polarnymi.",
];
